1.	Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-directories to find all duplicates files. Delete the found duplicate file


In [1]:
import hashlib
import os
directory=[]
dirpath="C:/Users/yatekumar/Desktop/files"


for(dir_path,dir_names,file_name) in os.walk(dirpath):
    directory.extend(file_name)

hashes = {}
result = set()
for i in range(len(directory)):
    fileObj = open('C:/Users/yatekumar/Desktop/files/'+directory[i],'r')
    content = fileObj.read()
    content=str(content)
    
    message = hashlib.sha256()
    message.update(bytes(content, 'utf-8'))
    hashcode=message.hexdigest()
    
    if hashcode in hashes.keys():
        result.add(hashes[hashcode])
        result.add(directory[i])
        
    else:
        hashes[hashcode]=directory[i]
        
print(result)
        
    


{'test.txt', 'fakfile.txt', 'New Text Document.txt'}


2.	Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters. Using these packages [random, strings]



In [2]:
import random 
import string

def genPass():
    upperletters=string.ascii_uppercase
    lowerletters=string.ascii_lowercase
    digits = [1,2,3,4,5,6,7,8,9,0]
    special=["<",">","?","!","@","#","$","%","&"]
    
    password = random.choice(upperletters)+random.choice(lowerletters)+random.choice(lowerletters)+str(random.choice(digits))+str(random.choice(digits))+random.choice(special)
    
        
    return "generated password is = "+password

genPass()
    

'generated password is = Ust17@'

3.	Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.



In [22]:
## import numpy as np
import math
def isPrime(num):
    
    for i in range(2,int(math.sqrt(num))+1):
        if num%2==0:
            return False;

    return True;

#Taking input
rows = int(input())
cols = int(input())

# declaring array with ones
arr = np.ones((rows,cols),'float')

# initialise array with user values

for i in range(rows):
    for j in range(cols):
        arr[i][j] = int(input())
        
        
# replace prime number by cube of the number
position=-1
for i in range(rows):
    for j in range(cols):
        position+=1
        if isPrime(position):
            arr[i][j] = arr[i][j]*arr[i][j]*arr[i][j]

print(arr)


4
4
2
3
6
2
6
5
2
1
4
6
7
8
2
4
2
4
[[  8.  27. 216.   8.]
 [  6. 125.   2.   1.]
 [  4. 216.   7. 512.]
 [  2.  64.   2.  64.]]


4.	Python program to get the sum of every cubed value and its previous integer. 

In [23]:
## import numpy as np
import math
def isPrime(num):
    
    for i in range(2,int(math.sqrt(num))+1):
        if num%2==0:
            return False;

    return True;

#Taking input
rows = int(input())
cols = int(input())

# declaring array with ones
arr = np.ones((rows,cols),'float')

# initialise array with user values

for i in range(rows):
    for j in range(cols):
        arr[i][j] = int(input())
        
        
# replace prime number by cube of the number
position=-1
previous = 0
sum=0
for i in range(rows):
    for j in range(cols):
        position+=1
        if isPrime(position):
            arr[i][j] = arr[i][j]*arr[i][j]*arr[i][j]
            sum=sum+arr[i][j]+previous
            
        previous = arr[i][j]
print(arr)
print(sum)


3
3
1
2
4
5
2
6
8
4
3
[[  1.   8.  64.]
 [125.   2. 216.]
 [  8.  64.   3.]]
561.0


5.Given two arrays, find their intersection. Examples:

Input:  arr1[] = [1, 3, 4, 5, 7]
        arr2[] = [2, 3, 5, 6]


In [8]:
import numpy as mp

arr1 = [1, 3, 4, 5, 7]
arr2 = [2, 3, 5, 6]

def intersection(lst1, lst2):
    res = [value for value in lst1 if value in lst2]
    return res

intersection(arr1,arr2)

[3, 5]

6.	Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [15]:
arr = np.ones((7,7),"int64")

position=1
for i in range(7):
    for j in range(7):
        if i==0 and j==0:
            arr[0][0]=7
            position+=1
        else:
            arr[i][j]=7*position
            position+=1
            
print(arr)
print(arr[6][6])

[[  7  14  21  28  35  42  49]
 [ 56  63  70  77  84  91  98]
 [105 112 119 126 133 140 147]
 [154 161 168 175 182 189 196]
 [203 210 217 224 231 238 245]
 [252 259 266 273 280 287 294]
 [301 308 315 322 329 336 343]]
343


In [16]:
import numpy as np
rows = int(input())
col = int(input())

arr = np.ones((rows,col),'int8')

for i in range(rows):
    for j in range(col):
        if (i+j)%2==1:
            arr[i][j]=0
            
print(arr)

8
8
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [17]:
arr = [['A','B','C','D'],
       ['E','F','G','H'],
       ['I','a','K','L'],
       ['M','N','o','P'],
       ['Q','R','S','T'],
       ['U','0','W','O']]
counter=0

for i in range(len(arr)):
    for j in range(len(arr[0])):
        if arr[i][j]=='A' or arr[i][j]=='E' or arr[i][j]=='I' or arr[i][j]=='O' or arr[i][j]=='U'or arr[i][j] =='a' or arr[i][j]=='e' or arr[i][j]=="i" or arr[i][j]=='o' or arr[i][j]=='u':
            arr[i][j]=np.nan
            counter+=1
                

print(arr)
print("Totel vowels are = ",counter)

[[nan, 'B', 'C', 'D'], [nan, 'F', 'G', 'H'], [nan, nan, 'K', 'L'], ['M', 'N', nan, 'P'], ['Q', 'R', 'S', 'T'], [nan, '0', 'W', nan]]
Totel vowels are =  7
